version: '3'
services:
  nginx:
    build:
      dockerfile: nginx.Dockerfile
      context: .
    ports:
      - "80:80"
  flask:
    build:
      dockerfile: flask.Dockerfile
      context: .
  django:
    build:
      dockerfile: django.Dockerfile
      context: .
